# Generated by Django 2.2.2 on 2019-06-23 21:33

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificadoHr', models.IntegerField()),
                ('nombreH', models.CharField(max_length=60)),
                ('cantidadH', models.IntegerField()),
            ],
            managers=[
                ('herramientas', django.db.models.manager.Manager()),
            ],
        ),
    ]
