# Generated by Django 2.2.2 on 2019-06-23 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_herramienta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herramienta',
            old_name='cantidadH',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='herramienta',
            old_name='identificadoHr',
            new_name='identificador',
        ),
        migrations.RenameField(
            model_name='herramienta',
            old_name='nombreH',
            new_name='nombre',
        ),
    ]
