# Generated by Django 2.2.2 on 2019-06-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0004_insumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='medida',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
