# Generated by Django 2.2.2 on 2019-06-23 23:08

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0005_insumo_medida'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.IntegerField()),
                ('nombre', models.CharField(max_length=60)),
                ('cantidad', models.IntegerField()),
            ],
            managers=[
                ('epps', django.db.models.manager.Manager()),
            ],
        ),
    ]
