# Generated by Django 2.2.7 on 2019-11-24 23:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaVentaGminox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cliente', models.CharField(max_length=100)),
                ('NumeroFactura', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('Fecha', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('Monto', models.BigIntegerField(blank=True, default=0, null=True)),
                ('Iva', models.BigIntegerField(blank=True, default=0, null=True)),
                ('Total', models.BigIntegerField(blank=True, default=0, null=True)),
                ('pdf', models.FileField(upload_to='facturasventa/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
        migrations.AlterField(
            model_name='facturacompragminox',
            name='Iva',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='facturacompragminox',
            name='Monto',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='facturacompragminox',
            name='Total',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
