# Generated by Django 2.2.7 on 2019-11-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_auto_20191123_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompragminox',
            name='NumeroFactura',
            field=models.PositiveIntegerField(blank=(None, 0)),
        ),
    ]
