# Generated by Django 2.2.7 on 2019-11-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0004_auto_20191123_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompragminox',
            name='Total',
            field=models.IntegerField(blank=(None, 0)),
        ),
    ]
