# Generated by Django 2.2.7 on 2019-12-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_auto_20191124_2052'),
        ('facturas', '0006_auto_20191123_1944'),
    ]

    operations = [
    ]
