# Generated by Django 2.2.5 on 2019-09-11 03:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_herramienta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('medida', models.FloatField()),
                ('cantidad', models.IntegerField()),
            ],
            managers=[
                ('insumos', django.db.models.manager.Manager()),
            ],
        ),
    ]
