# Generated by Django 2.2.5 on 2019-09-14 20:45

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20190914_0020'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='herramienta',
            managers=[
                ('herramientas', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='insumo',
            managers=[
                ('insumos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='despunte',
            name='cantidad',
        ),
    ]
