# Generated by Django 2.2.7 on 2019-11-12 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
