# Generated by Django 2.0.2 on 2019-11-15 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_auto_20191114_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='dirección',
            new_name='direccion',
        ),
    ]
