# Generated by Django 2.0.2 on 2019-10-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('rut', models.CharField(max_length=11)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('giro', models.CharField(max_length=60)),
                ('ciudad', models.CharField(max_length=30)),
                ('contacto', models.CharField(max_length=60)),
            ],
        ),
    ]
