# Generated by Django 2.2.5 on 2019-11-21 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cotizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciongminox',
            name='pdf',
            field=models.FileField(upload_to='cotizaciones/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
