# Generated by Django 2.2.7 on 2019-11-24 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cotizacion', '0002_auto_20191114_0141'),
        ('Cotizacion', '0002_auto_20191121_1824'),
    ]

    operations = [
    ]
